id: cb2c1ebe7abf4238a3851520b01b5262
initial_creation_type: ocr
source_metadata:
  volumes:
    06bff58e324045808e7a9eb9c59ead3d:
      base_file: v024.txt
      image_group_id: I1PD95869
      title: ''
      total_pages: 1586
      volume_number: 24
